// console.log(document.body.childNodes)
// console.log(document.body.childNodes[0])
// console.log(document.body.childNodes[1])
// console.log(document.body.childNodes[2])
// console.log(document.body.childNodes[3])
// console.log(document.body.firstChild)
// console.log(document.body.lastChild)
// console.log(document.body.childNodes[1].childNodes)
// // console.log(document.body.childNodes[1].children)
// console.log(document.body.firstElementChild)
// console.log(document.body.firstElementChild.childNodes)
// console.log(document.body.lastElementChild)
// console.log(document.body.firstElementChild.nextElementSibling)
// console.log(document.body.firstElementChild.parentNode)
// console.log(document.body.firstElementChild.children[2].style.backgroundColor = "red")
console.log(document.body.children[1].rows)
console.log(document.body.children[1].thead)


